---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1
  - 2.4
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4"
  - PUPPET_VERSION="~> 5"
matrix:
  exclude:
  - rvm: 2.1
    env: PUPPET_VERSION="~> 5"
  - rvm: 2.4
    env: PUPPET_VERSION="~> 4"
